import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  bool get isChinese => locale.languageCode == 'zh';

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  String tr(String key, [Map<String, Object?> values = const {}]) {
    var text = (isChinese ? _zh : _en)[key] ?? key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return text;
  }

  static bool isSimplifiedChinese(Locale locale) {
    if (locale.languageCode.toLowerCase() != 'zh') return false;
    final script = locale.scriptCode?.toLowerCase();
    if (script == 'hant') return false;
    if (script == 'hans') return true;
    final country = locale.countryCode?.toUpperCase();
    return country == 'CN' || country == 'SG';
  }

  static Locale resolveSystemLocales(List<Locale>? locales) {
    final systemLocale = locales?.isNotEmpty == true
        ? locales!.first
        : PlatformDispatcher.instance.locale;
    return isSimplifiedChinese(systemLocale)
        ? const Locale('zh', 'CN')
        : const Locale('en');
  }

  static const delegate = _AppLocalizationsDelegate();
  static const supportedLocales = [Locale('en'), Locale('zh', 'CN')];

  static const Map<String, String> _zh = {
    // 通用
    'appName': 'Ramizom System Health Toolkit',
    'retry': '重试',
    'refresh': '刷新',
    'cancel': '取消',
    'unknown': '未知',
    'notAvailable': '暂无数据',
    'notProvided': '设备未提供',
    'times': '{count} 次',
    'days': '{count} 天',
    'yearsDays': '{years} 年 {days} 天',
    // 导航
    'home': '主页',
    'privacySecurity': '隐私与安全',
    'powerPerformance': '电池与性能',
    'diskHealth': '磁盘健康',
    'recommendations': '推荐设置',
    'settings': '设置',
    'security': '安全',
    'battery': '电池',
    'other': '其他',
    // 设置
    'appearance': '外观',
    'language': '语言',
    'appLanguage': '应用语言',
    'followSystem': '跟随系统',
    'simplifiedChinese': '简体中文',
    'english': 'English',
    'themeMode': '主题模式',
    'light': '浅色',
    'dark': '深色',
    'themeColor': '主题色',
    'chooseThemeColor': '选择应用颜色',
    'dataRefresh': '数据刷新',
    'homeRefreshRate': '主页刷新间隔',
    'everySeconds': '每 {seconds} 秒',
    'seconds': '{seconds} 秒',
    'about': '关于',
    'applicationName': '产品名称',
    'version': '版本',
    'developer': '开发者',
    'developerName': '苦力怕教授',
    'developmentDate': '开发日期',
    'developmentDateValue': '2026年6月21日 至 2026年7月25日',
    'website': '官网',
    'visitWebsite': '访问官网',
    'privacyPolicy': '隐私策略',
    'openPrivacyPolicy': '查看隐私策略',
    // 主页
    'memory': '内存',
    'systemDisk': '系统盘 (C:)',
    'usedPercent': '已用 {percent}%',
    'deviceOverview': '设备概览',
    'processor': '处理器',
    'unknownProcessor': '未找到处理器信息',
    'graphics': '显卡',
    'noGpu': '未找到显卡信息',
    'disk': '磁盘',
    'loading': '正在获取…',
    'diskCount': '{size} GB · {count} 块',
    'cannotEvaluate': '暂时无法评估',
    'runningNormally': '运行正常',
    'needsAttention': '需要关注',
    'cpuHigh': 'CPU 使用率较高（{percent}%）',
    'memoryHigh': '内存使用率较高（{percent}%）',
    'diskSpaceLow': '系统盘空间不足（{percent}%）',
    'systemStatus': '运行状态',
    'waitingForMetrics': '正在获取系统数据。',
    'allNormal': '各项状态正常。',
    'quickLinks': '快捷入口',
    'systemVersion': '系统版本',
    'windowsUpdate': 'Windows 更新',
    'windowsSecurity': 'Windows 安全中心',
    'firewall': '防火墙',
    'storage': '存储',
    'power': '电源',
    'apps': '应用',
    'startupApps': '启动项',
    'privacy': '隐私',
    // 磁盘
    'diskSlow': '磁盘响应较慢，仍在读取。',
    'noDiskInfo': '未找到磁盘信息',
    'good': '良好',
    'warning': '警告',
    'abnormal': '异常',
    'limitedDiskData': '此设备没有提供更多健康数据。',
    'healthPercent': '健康度',
    'healthAssessment': '健康状态',
    'lifetimeRead': '累计读取',
    'bootRead': '本次开机读取',
    'lifetimeWrite': '累计写入',
    'bootWrite': '本次开机写入',
    'currentTemperature': '当前温度',
    'maxTemperature': '最高温度',
    'powerOnTime': '使用时间',
    'lifeUsed': '寿命消耗',
    'readErrors': '读取错误',
    'writeErrors': '写入错误',
    'uncorrectedReadErrors': '严重读取错误',
    'uncorrectedWriteErrors': '严重写入错误',
    'maxReadLatency': '最高读取延迟',
    'maxWriteLatency': '最高写入延迟',
    'startStopCount': '启停次数',
    'headLoadCount': '磁头加载次数',
    'powerCycleCount': '开机次数',
    'unsafeShutdownCount': '异常断电',
    'mediaErrors': '介质错误',
    'mediaType': '磁盘类型',
    'operationalStatus': '运行状态',
    'busType': '接口类型',
    'firmwareVersion': '固件版本',
    'logicalSector': '逻辑扇区',
    'physicalSector': '物理扇区',
    'spindleSpeed': '转速',
    'replaceSoon': '建议更换',
    'checkDisk': '需要关注',
    'cannotAssess': '无法评估',
    'nearLifeLimit': '寿命即将耗尽',
    'halfLifeUsed': '寿命已用过半',
    'usedForLongTime': '使用时间较长',
    'statusGood': '状态良好',
    // 电池
    'windowsBatteryReport': '电池报告',
    'regenerate': '重新生成',
    'generatingBatteryReport': '正在读取电池报告…',
    'systemBattery': '系统电池',
    'chargeAtReport': '当前电量',
    'batteryHealthValue': '健康度 {percent}%',
    'reportTime': '报告时间：{time}',
    'designCapacity': '设计容量',
    'fullChargeCapacity': '最高容量',
    'remainingCapacity': '当前容量',
    'batteryHealth': '电池健康度',
    'cycleCount': '循环次数',
    'serialNumber': '序列号',
    'batteryDetails': '电池信息',
    'batteryUsageHistory': '电量使用记录',
    'batteryUsageSubtitle': '最近 14 天的电量变化',
    'noBatteryUsage': '最近没有放电记录',
    'capacityHistory': '容量变化',
    'capacityHistorySubtitle': '最高容量与设计容量的变化',
    'noCapacityHistory': '没有容量历史',
    'usefulPerformanceSettings': '常用设置',
    'powerAndBattery': '电源与电池',
    'powerAndBatteryDesc': '调整电源、睡眠和屏幕时间',
    'energyTips': '节能建议',
    'energyTipsDesc': '查看 Windows 节能建议',
    'graphicsSettings': '图形设置',
    'graphicsSettingsDesc': '选择应用使用的显卡',
    'startupApplications': '启动应用',
    'startupApplicationsDesc': '管理开机启动程序',
    'gameMode': '游戏模式',
    'gameModeDesc': '调整游戏模式',
    'batteryUsage': '电池使用情况',
    'batteryUsageDesc': '查看应用耗电',
    'noBattery': '未检测到电池。',
    // 隐私
    'privacyProtection': '隐私保护',
    'allProtectionsOn': '3 项保护均已开启',
    'protectionCount': '已开启 {count}/3 项',
    'microphoneProtection': '关闭麦克风访问',
    'microphoneProtectionDesc': '阻止应用使用麦克风',
    'microphoneProtectionImpact': '通话和录音会暂时无法使用',
    'screenProtection': '关闭录屏和截图',
    'screenProtectionDesc': '关闭 Windows 录屏和截图功能',
    'screenProtectionImpact': '部分第三方工具可能不受影响',
    'cameraProtection': '关闭摄像头访问',
    'cameraProtectionDesc': '阻止应用使用摄像头',
    'cameraProtectionImpact': '视频通话和相机应用会暂时无法使用',
    'privacyAdminNote': '更改时需要管理员权限。部分应用可能需要重启。',
    'privacySaved': '设置已更新。',
    'comingSoon': '即将推出',
    'privacyFailed': '设置未能更改。请确认管理员权限后重试。',
    'location': '定位',
    'camera': '相机',
    'microphone': '麦克风',
    'driveEncryption': '磁盘加密',
    'windowsPrivacySettings': 'Windows 隐私设置',
    // 推荐设置
    'turnOnDefender': '开启病毒防护',
    'turnOnDefenderDesc': '实时保护已关闭。建议立即开启。',
    'openWindowsSecurity': '打开安全中心',
    'turnOnFirewall': '开启防火墙',
    'turnOnFirewallDesc': '防火墙已关闭。建议立即开启。',
    'openFirewall': '打开防火墙',
    'installUpdates': '安装 Windows 更新',
    'installUpdatesDesc': '有 {count} 个更新等待安装。',
    'openWindowsUpdate': '打开 Windows 更新',
    'cleanSystemDisk': '清理系统盘',
    'cleanSystemDiskDesc': '系统盘已用 {percent}%。请释放一些空间。',
    'openStorage': '打开存储设置',
    'watchDiskSpace': '系统盘空间较少',
    'watchDiskSpaceDesc': '系统盘已用 {percent}%。建议清理。',
    'reduceMemory': '减少内存占用',
    'reduceMemoryDesc': '内存使用率为 {percent}%。请关闭不用的应用。',
    'watchBattery': '关注电池健康',
    'watchBatteryDesc': '电池健康度为 {percent}%。',
    'viewBatteryUsage': '查看电池使用',
    'reduceCpu': '减少 CPU 占用',
    'reduceCpuDesc': 'CPU 使用率为 {percent}%。请检查正在运行的应用。',
    'considerBitLocker': '开启磁盘加密',
    'considerBitLockerDesc': '系统盘未加密。开启后可更好地保护数据。',
    'systemLooksGood': '系统状态良好',
    'noActionNeeded': '目前没有需要处理的问题。',
    'networkRepair': '修复网络',
    'networkRepairConfirm': '将刷新 DNS 并重置网络组件。部分 VPN 可能需要重新连接。',
    'continueRepair': '继续修复',
    'pauseUpdates': '暂缓系统更新',
    'reapplyPause': '重新应用暂缓设置',
    'pauseUpdatesConfirm': '将 Windows 更新暂缓至 2042-09-05。期间可能收不到安全更新。',
    'reapplyPauseConfirm': '将重新写入并检查现有设置。截止日期仍为 2042-09-05。',
    'confirmPause': '确认暂缓',
    'reapply': '重新应用',
    'resumeUpdates': '恢复更新',
    'resumeUpdatesTitle': '恢复系统更新',
    'resumeUpdatesConfirm': '将恢复暂缓前的更新设置。Windows 可以再次检查更新。',
    'repairShell': '修复桌面和任务栏图标',
    'repairShellConfirm': '将刷新 Windows 图标缓存。不会关闭桌面或正在使用的应用。',
    'refreshAndRestart': '刷新图标',
    'stillChecking': '检测时间较长，仍在后台继续。',
    'recommendedForYou': '推荐操作',
    'checkAgain': '重新检测',
    'maintenanceTools': '所有工具',
    'updatesPausedUntil': '已暂缓至 2042-09-05',
    'pauseUntil': '暂缓至 2042-09-05',
    'repairNetworkDesc': '刷新 DNS 和网络组件',
    'repair': '修复',
    'repairShellDesc': '刷新桌面和任务栏图标',
    'highPriority': '优先处理',
    'recommended': '建议处理',
    'optional': '可选',
    'statusFine': '状态良好',
    'actionCompleted': '操作完成。',
    'actionFailed': '操作失败。请重试。',
  };

  static const Map<String, String> _en = {
    'appName': 'Ramizom System Health Toolkit',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'cancel': 'Cancel',
    'unknown': 'Unknown',
    'notAvailable': 'Not available',
    'notProvided': 'Not provided',
    'times': '{count} times',
    'days': '{count} days',
    'yearsDays': '{years} years {days} days',
    'home': 'Home',
    'privacySecurity': 'Privacy & security',
    'powerPerformance': 'Battery & performance',
    'diskHealth': 'Disk health',
    'recommendations': 'Recommended settings',
    'settings': 'Settings',
    'security': 'Security',
    'battery': 'Battery',
    'other': 'More',
    'appearance': 'Appearance',
    'language': 'Language',
    'appLanguage': 'App language',
    'followSystem': 'Use system setting',
    'simplifiedChinese': '简体中文',
    'english': 'English',
    'themeMode': 'Theme',
    'light': 'Light',
    'dark': 'Dark',
    'themeColor': 'Accent color',
    'chooseThemeColor': 'Choose an app color',
    'dataRefresh': 'Data refresh',
    'homeRefreshRate': 'Home refresh rate',
    'everySeconds': 'Every {seconds} seconds',
    'seconds': '{seconds} sec',
    'about': 'About',
    'applicationName': 'Product name',
    'version': 'Version',
    'developer': 'Developer',
    'developerName': 'Professor Creeper',
    'developmentDate': 'Development date',
    'developmentDateValue': 'June 21, 2026 – July 25, 2026',
    'website': 'Website',
    'visitWebsite': 'Visit website',
    'privacyPolicy': 'Privacy policy',
    'openPrivacyPolicy': 'View privacy policy',
    'memory': 'Memory',
    'systemDisk': 'System drive (C:)',
    'usedPercent': '{percent}% used',
    'deviceOverview': 'Device overview',
    'processor': 'Processor',
    'unknownProcessor': 'Processor information unavailable',
    'graphics': 'Graphics',
    'noGpu': 'Graphics information unavailable',
    'disk': 'Disk',
    'loading': 'Loading…',
    'diskCount': '{size} GB · {count} drives',
    'cannotEvaluate': 'Not enough data',
    'runningNormally': 'All good',
    'needsAttention': 'Needs attention',
    'cpuHigh': 'CPU usage is high ({percent}%)',
    'memoryHigh': 'Memory usage is high ({percent}%)',
    'diskSpaceLow': 'System drive is low on space ({percent}%)',
    'systemStatus': 'System status',
    'waitingForMetrics': 'Getting system data.',
    'allNormal': 'Everything looks good.',
    'quickLinks': 'Quick links',
    'systemVersion': 'Windows version',
    'windowsUpdate': 'Windows Update',
    'windowsSecurity': 'Windows Security',
    'firewall': 'Firewall',
    'storage': 'Storage',
    'power': 'Power',
    'apps': 'Apps',
    'startupApps': 'Startup apps',
    'privacy': 'Privacy',
    'diskSlow': 'The disk is taking longer to respond.',
    'noDiskInfo': 'No disk information found',
    'good': 'Good',
    'warning': 'Warning',
    'abnormal': 'Problem',
    'limitedDiskData': 'This device does not provide more health details.',
    'healthPercent': 'Health',
    'healthAssessment': 'Health status',
    'lifetimeRead': 'Total read',
    'bootRead': 'Read since startup',
    'lifetimeWrite': 'Total written',
    'bootWrite': 'Written since startup',
    'currentTemperature': 'Temperature',
    'maxTemperature': 'Maximum temperature',
    'powerOnTime': 'Power-on time',
    'lifeUsed': 'Life used',
    'readErrors': 'Read errors',
    'writeErrors': 'Write errors',
    'uncorrectedReadErrors': 'Serious read errors',
    'uncorrectedWriteErrors': 'Serious write errors',
    'maxReadLatency': 'Maximum read delay',
    'maxWriteLatency': 'Maximum write delay',
    'startStopCount': 'Start/stop count',
    'headLoadCount': 'Head load count',
    'powerCycleCount': 'Power cycles',
    'unsafeShutdownCount': 'Unsafe shutdowns',
    'mediaErrors': 'Media errors',
    'mediaType': 'Drive type',
    'operationalStatus': 'Status',
    'busType': 'Connection',
    'firmwareVersion': 'Firmware',
    'logicalSector': 'Logical sector',
    'physicalSector': 'Physical sector',
    'spindleSpeed': 'Speed',
    'replaceSoon': 'Replace soon',
    'checkDisk': 'Needs attention',
    'cannotAssess': 'Cannot assess',
    'nearLifeLimit': 'Near end of life',
    'halfLifeUsed': 'Over half used',
    'usedForLongTime': 'Used for a long time',
    'statusGood': 'Good',
    'windowsBatteryReport': 'Battery report',
    'regenerate': 'Generate again',
    'generatingBatteryReport': 'Reading the battery report…',
    'systemBattery': 'System battery',
    'chargeAtReport': 'Current charge',
    'batteryHealthValue': 'Health {percent}%',
    'reportTime': 'Report time: {time}',
    'designCapacity': 'Design capacity',
    'fullChargeCapacity': 'Full charge capacity',
    'remainingCapacity': 'Current capacity',
    'batteryHealth': 'Battery health',
    'cycleCount': 'Cycle count',
    'serialNumber': 'Serial number',
    'batteryDetails': 'Battery details',
    'batteryUsageHistory': 'Battery usage history',
    'batteryUsageSubtitle': 'Charge changes over the last 14 days',
    'noBatteryUsage': 'No recent discharge records',
    'capacityHistory': 'Capacity history',
    'capacityHistorySubtitle':
        'Full charge capacity compared with design capacity',
    'noCapacityHistory': 'No capacity history',
    'usefulPerformanceSettings': 'Useful settings',
    'powerAndBattery': 'Power & battery',
    'powerAndBatteryDesc': 'Change power, sleep, and screen settings',
    'energyTips': 'Energy recommendations',
    'energyTipsDesc': 'View Windows energy tips',
    'graphicsSettings': 'Graphics settings',
    'graphicsSettingsDesc': 'Choose which GPU an app uses',
    'startupApplications': 'Startup apps',
    'startupApplicationsDesc': 'Manage apps that start with Windows',
    'gameMode': 'Game Mode',
    'gameModeDesc': 'Change Game Mode settings',
    'batteryUsage': 'Battery usage',
    'batteryUsageDesc': 'See power use by app',
    'noBattery': 'No battery was found.',
    'privacyProtection': 'Privacy protection',
    'allProtectionsOn': 'All 3 protections are on',
    'protectionCount': '{count}/3 protections are on',
    'microphoneProtection': 'Block microphone access',
    'microphoneProtectionDesc': 'Stop apps from using the microphone',
    'microphoneProtectionImpact':
        'calls and recordings will not work while this is on',
    'screenProtection': 'Block screen capture',
    'screenProtectionDesc':
        'Turn off Windows recording and screenshot features',
    'screenProtectionImpact': 'some third-party tools may still work',
    'cameraProtection': 'Block camera access',
    'cameraProtectionDesc': 'Stop apps from using the camera',
    'cameraProtectionImpact':
        'video calls and camera apps will not work while this is on',
    'privacyAdminNote':
        'Administrator approval is required. Some apps may need to restart.',
    'privacySaved': 'Settings updated.',
    'comingSoon': 'Coming soon',
    'privacyFailed':
        'The setting could not be changed. Approve administrator access and try again.',
    'location': 'Location',
    'camera': 'Camera',
    'microphone': 'Microphone',
    'driveEncryption': 'Device encryption',
    'windowsPrivacySettings': 'Windows privacy settings',
    'turnOnDefender': 'Turn on virus protection',
    'turnOnDefenderDesc': 'Real-time protection is off. Turn it on now.',
    'openWindowsSecurity': 'Open Windows Security',
    'turnOnFirewall': 'Turn on the firewall',
    'turnOnFirewallDesc': 'The firewall is off. Turn it on now.',
    'openFirewall': 'Open firewall settings',
    'installUpdates': 'Install Windows updates',
    'installUpdatesDesc': '{count} updates are ready to install.',
    'openWindowsUpdate': 'Open Windows Update',
    'cleanSystemDisk': 'Free up disk space',
    'cleanSystemDiskDesc':
        'The system drive is {percent}% full. Free up some space.',
    'openStorage': 'Open Storage settings',
    'watchDiskSpace': 'System drive is getting full',
    'watchDiskSpaceDesc': 'The system drive is {percent}% full.',
    'reduceMemory': 'Free up memory',
    'reduceMemoryDesc':
        'Memory usage is {percent}%. Close apps you are not using.',
    'watchBattery': 'Check battery health',
    'watchBatteryDesc': 'Battery health is {percent}%.',
    'viewBatteryUsage': 'View battery usage',
    'reduceCpu': 'Reduce CPU usage',
    'reduceCpuDesc': 'CPU usage is {percent}%. Check your open apps.',
    'considerBitLocker': 'Turn on device encryption',
    'considerBitLockerDesc':
        'The system drive is not encrypted. Encryption helps protect your data.',
    'systemLooksGood': 'Your system looks good',
    'noActionNeeded': 'There is nothing you need to do right now.',
    'networkRepair': 'Fix network',
    'networkRepairConfirm':
        'This refreshes DNS and resets Windows network sockets. Some VPNs may need to reconnect.',
    'continueRepair': 'Continue',
    'pauseUpdates': 'Pause Windows updates',
    'reapplyPause': 'Reapply pause settings',
    'pauseUpdatesConfirm':
        'Windows updates will be paused until September 5, 2042. You may miss security updates.',
    'reapplyPauseConfirm':
        'The current pause settings will be written and checked again. The end date stays September 5, 2042.',
    'confirmPause': 'Pause updates',
    'reapply': 'Reapply',
    'resumeUpdates': 'Resume',
    'resumeUpdatesTitle': 'Resume Windows updates',
    'resumeUpdatesConfirm':
        'This restores the update settings saved before the pause. Windows can check for updates again.',
    'repairShell': 'Fix desktop and taskbar icons',
    'repairShellConfirm':
        'This refreshes the Windows icon cache. It will not close the desktop or your open apps.',
    'refreshAndRestart': 'Refresh icons',
    'stillChecking': 'The check is taking longer. It is still running.',
    'recommendedForYou': 'Recommended actions',
    'checkAgain': 'Check again',
    'maintenanceTools': 'All Tools',
    'updatesPausedUntil': 'Paused until Sep 5, 2042',
    'pauseUntil': 'Pause until Sep 5, 2042',
    'repairNetworkDesc': 'Refresh DNS and network sockets',
    'repair': 'Fix',
    'repairShellDesc': 'Refresh desktop and taskbar icons',
    'highPriority': 'High priority',
    'recommended': 'Recommended',
    'optional': 'Optional',
    'statusFine': 'All good',
    'actionCompleted': 'Done.',
    'actionFailed': 'The action failed. Try again.',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      locale.languageCode == 'en' || locale.languageCode == 'zh';

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
